name: SMM2Properties CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Node.js (v${{ matrix.node-version }}) configuration
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - name: Dependencies installation
        run: npm ci
      - name: Application deployment
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
