name: SMM Encyclopedia CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout of the repository
        uses: actions/checkout@v3

      - name: Configuration of the Node v${{matrix.node-version}} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Installation of the dependencies (for NPM)
        run: npm ci

      - name: Conversion from CSV to Json
        run: npm run convert-csv-to-json

      - name: Copying the images for the CSS
        run: npm run copy-images-for-css

      - name: Copying the locale on the "/src" folder
        run: npm run copy-locale-to-src

      - name: Deployment of the application
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN_SMM_ENCYCLOPEDIA }}
          repository: ${{ github.repository }}
