name: SMM2Properties CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Git bot configuration
        run: |
          git config user.email "$(git log --format='%ae' HEAD^!)"
          git config user.name "$(git log --format='%an' HEAD^!)"
      - name: Node.js (v${{ matrix.node-version }}) configuration
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Dependencies installation
        run: npm ci
      - name: Application deployment
        run: npm run deploy
      - name: Commit files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git commit -m "Fix a[href] in Webflow exported html"
          git push github HEAD:${GITHUB_REF}