name: SMM2Properties CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Git bot configuration
        run: |
          git config user.email "$(git log --format='%ae' HEAD^!)"
          git config user.name "$(git log --format='%an' HEAD^!)"
          git remote set-url origin git@github.com:joooKiwi/every-SMM2-properties.git
      - name: Node.js (v${{ matrix.node-version }}) configuration
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Dependencies installation
        run: npm ci
      - name: Application deployment
        run: npm run deploy
